version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: spring-boot-mongo-app-2
    depends_on:
      - db
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://db:27017/test
    ports:
      - 8080:8080
  db:
    image: mongo
    ports:
      - 27017:27017
